# Generated by Django 4.2.11 on 2024-03-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('measures', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('price', models.FloatField()),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='safafitapp.size')),
            ],
        ),
    ]
