# Generated by Django 4.2.11 on 2024-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safafitapp', '0003_customer_shop_orderline_order_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrator'), ('CUSTOMER', 'Customer'), ('EMPLOYEE', 'Employee')], default='CUSTOMER', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
