# Generated by Django 4.2.11 on 2024-04-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safafitapp', '0005_customer_user_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=500)),
                ('posicion', models.IntegerField()),
                ('premiado', models.BooleanField()),
            ],
        ),
    ]
